[build]
    publish = "dist"
    command = "npm run build"


[[redirects]]
  from = "https://legendary-learning.netlify.app"
  to = "https://legendary-courses.netlify.app"
  status = 301
  force = true



[[redirects]]
  from = "https://legendary-learning.netlify.app"
  to = "https://legendary-courses.netlify.app"
  status = 200
  force = true


